CREATE TABLE IF NOT EXISTS destinos (
	id SERIAL PRIMARY KEY,
	ciudad VARCHAR(100) NOT NULL,
	pais VARCHAR(100) NOT NULL,
	creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_destinos_ciudad_pais_normalizado
ON destinos (LOWER(TRIM(ciudad)), LOWER(TRIM(pais)));

CREATE TABLE IF NOT EXISTS hospedajes (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre VARCHAR(200) NOT NULL,
	tipo VARCHAR(20) CHECK (tipo IN ('hotel', 'airbnb', 'otro')),
	precio_noche DECIMAL(10, 2),
	calificacion DECIMAL(3, 2),
	direccion VARCHAR(200),
	url_reserva TEXT,
	destino_id INT NOT NULL REFERENCES destinos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_hospedajes_destino_id ON hospedajes(destino_id);

CREATE TABLE IF NOT EXISTS evaluaciones_ia (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	puntos_fuertes TEXT,
	puntos_debiles TEXT,
	score_calidad_precio INT CHECK (score_calidad_precio BETWEEN 1 AND 10),
	resumen_ejecutivo TEXT,
	hospedaje_id INT UNIQUE REFERENCES hospedajes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS atracciones (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre TEXT,
	categoria TEXT,
	distancia_km DECIMAL(4,2),
	precio_estimado DECIMAL(10,2) DEFAULT 0.00,
	hospedaje_id INT REFERENCES hospedajes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    correo VARCHAR(60) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS busquedas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    destino_id INT NOT NULL REFERENCES destinos(id) ON DELETE CASCADE,
    zona VARCHAR(100) NOT NULL,
    presupuesto DECIMAL(10, 2) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,

    CONSTRAINT chk_busqueda_presupuesto CHECK (presupuesto > 0),

    CONSTRAINT chk_busqueda_fechas CHECK (fecha_fin >= fecha_inicio)
);


CREATE TABLE IF NOT EXISTS recomendaciones (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    busqueda_id INT NOT NULL REFERENCES busquedas(id) ON DELETE CASCADE,
    hospedaje_id INT NOT NULL REFERENCES hospedajes(id) ON DELETE CASCADE,
    posicion INT NOT NULL,

    CONSTRAINT chk_recomendacion_posicion CHECK (posicion BETWEEN 1 AND 3),

    CONSTRAINT uq_recomendacion_busqueda_posicion UNIQUE (busqueda_id, posicion),

    CONSTRAINT uq_recomendacion_busqueda_hospedaje UNIQUE (busqueda_id, hospedaje_id)
);