CREATE TABLE IF NOT EXISTS destinos (
	id SERIAL PRIMARY KEY,
	ciudad VARCHAR(100) NOT NULL,
	pais VARCHAR(100) NOT NULL,
	creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hospedajes (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre VARCHAR(200) NOT NULL,
	tipo VARCHAR(20) CHECK (tipo IN ('hotel', 'airbnb', 'otro')),
	precio_noche DECIMAL(10, 2),
	calificacion DECIMAL(3, 2),
	direccion VARCHAR(200),
	url_reserva TEXT,
	destino_id INT REFERENCES destinos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS evaluaciones_ia (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	puntos_fuertes TEXT,
	puntos_debiles TEXT,
	score_calidad_precio INT CHECK (score_calidad_precio BETWEEN 1 AND 10),
	resumen_ejecutivo TEXT,
	hospedaje_id INT UNIQUE REFERENCES hospedajes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS atracciones (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre TEXT,
	categoria TEXT,
	distancia_km DECIMAL(4,2),
	precio_estimado DECIMAL(10,2) DEFAULT 0.00,
	hospedaje_id INT REFERENCES hospedajes(id) ON DELETE CASCADE
);